### ISSUE TITLE
Measurement doesn't work on tokens with imprecise sense (module integration with vision 5e)

### ISSUE THREAD

**Issue by dineshm72** [Aedif/tactical-grid#17]
If using the vision 5e module in v11, tokens that are not visible but are within the hearing threshold show up as "imprecise" tokens with a rippled water icon to indicate you can hear them but can't identify them visually.  These tokens are targetable however.

The measurement view of tactical grid does not show the distance to these tokens however.  Since they are targetable, imo the distance to them should be shown (or at least there should be an option to do so).

I know the visual indication is coming from v5e, so you might say that it's an issue with the other module, but I'm not exactly sure what it's changing that makes the measurement not show for them.  Since it's a targetable token it seems like it should just work.

<img width="485" alt="image" src="https://github.com/Aedif/tactical-grid/assets/2231877/d91bfcbd-57a4-4e31-9cb8-1f2f22dae71a">

**Comment by dineshm72** [comment]
edit: well, I figured out the difference.  In core without v5e those tokens are just invisible, so I guess it makes sense.  It would be nice if this module integrated with v5e to show these imprecise tokens, however.

(In the above example, the top token is not visible because it is outside of the light source, and the right token is invisible, just as an FYI.)

**Comment by Aedif** [comment]
As you said, the issue was that the tokens were being rendered invisible, and as such the module would exclude them from the measurement calculations in order to avoid invisible tokens being revealed to the players.

In the latest release (https://github.com/Aedif/tactical-grid/releases/tag/1.17.0) the module now checks `token.impreciseVisible` to decide whether those tokens should be an exception.
